from __future__ import annotations

"""
Bundled LeetCode problem metadata lookup.

problems_meta.json is generated by scripts/fetch_meta.py and shipped
with the package. It maps problem_id (string) to a metadata dict.

insights.json is generated by scripts/generate_insights.py and shipped
with the package. It maps problem_id (string) to a one-sentence insight.

All public functions are safe to call with an unknown ID — they return
None / False / "" rather than raising.
"""

import json
from dataclasses import dataclass
from functools import lru_cache
from importlib import resources
from typing import Optional


@dataclass(frozen=True)
class ProblemMeta:
    problem_id: str
    title: str
    slug: str
    difficulty: str        # "easy" | "medium" | "hard"
    tags: list[str]
    url: str
    paid: bool


@lru_cache(maxsize=1)
def _load() -> dict[str, dict]:
    """Load and cache the bundled problems_meta.json. Called once per process."""
    pkg = resources.files("leetrevive.data")
    text = (pkg / "problems_meta.json").read_text(encoding="utf-8")
    return json.loads(text)


@lru_cache(maxsize=1)
def _load_insights() -> dict[str, str]:
    """Load and cache insights.json. Returns empty dict if file missing/empty."""
    try:
        pkg = resources.files("leetrevive.data")
        text = (pkg / "insights.json").read_text(encoding="utf-8")
        data = json.loads(text)
        # Guard: must be a dict mapping str → str
        if isinstance(data, dict):
            return data
    except Exception:
        pass
    return {}


def lookup(problem_id: str) -> Optional[ProblemMeta]:
    """Return metadata for a known problem ID, or None if not found."""
    raw = _load().get(problem_id)
    if raw is None:
        return None
    return ProblemMeta(
        problem_id=problem_id,
        title=raw["title"],
        slug=raw["slug"],
        difficulty=raw["difficulty"],
        tags=raw["tags"],
        url=raw["url"],
        paid=raw.get("paid", False),
    )


def get_insight(problem_id: str) -> str:
    """Return the one-sentence algorithmic insight, or '' if not available."""
    return _load_insights().get(problem_id, "")


def is_known(problem_id: str) -> bool:
    return problem_id in _load()


def total() -> int:
    return len(_load())
